# Generated by Django 4.0.1 on 2022-01-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
